repomisc:
  repo:
    username:
      $type: str
    password:
      $type: str
    basicurl:
      $type: str
    owner:
      $type: str
    reponame:
      $type: str
    repopath:
      $type: str
    refspecs:
      $type: list
    commands:
      $type: dict
  repos:
    $value:
