repomisc:
  repo:
    username: miacro
    password: ""
    basicurl: https://github.com
    owner: miacro
  repos:
  - bootstrap
  - command-line-options
  - dockerwrapper
  - reponame: easycert
  - emacs.d
  - lisp-koans
  - miacro-overlay
  - miacropp
  - minesweeper
  - https://a:b@github.com/miacro/mlmisc
  - nginx.d
  - online-judge
  - pkget
  - git@github.com:miacro/profiles.git
  - pyconfigmanager
  - repomisc
  - stumpwm.d
  - utils
  - vim.d
  - https://github.com
